export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";

export const SET_LANGUAGE = "SET_LANGUAGE";

export const PAGINATE = "PAGINATE";



